# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lilutils}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kedar Mhaswade"]
  s.date = %q{2011-03-12}
  s.default_executable = %q{cli-demo}
  s.description = %q{Provides little utilties. It's a gem by a newbie, but I think it is quite useful. As of now, it provides a nicely abstracted out yes/no/cancel dialog box on a console.}
  s.email = %q{kedar.mhaswade@gmail.com}
  s.executables = ["cli-demo"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "History.txt",
    "Manifest.txt",
    "PostInstall.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/cli-demo",
    "lib/lilutils.rb",
    "lib/lilutils/algo_test_utils/data_sets.rb",
    "lib/lilutils/algo_test_utils_entry.rb",
    "lib/lilutils/cli/cli.rb",
    "lib/lilutils/cli_entry.rb",
    "lib/lilutils/misc/binary_search.rb",
    "lib/lilutils/misc/misc.rb",
    "lib/lilutils/misc/pascal.rb",
    "lib/lilutils/misc_entry.rb",
    "lilutils.gemspec",
    "script/console",
    "script/destroy",
    "script/generate",
    "test/algo_test_utils/data_sets_test.rb",
    "test/cli/cli_basic_test.rb",
    "test/misc/binary_search_test.rb",
    "test/misc/misc_pascal_test.rb",
    "test/test_helper.rb",
    "test/test_lilutils.rb"
  ]
  s.homepage = %q{http://github.com/kedarmhaswade/lilutils}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Little utilities for everyone}
  s.test_files = [
    "test/algo_test_utils/data_sets_test.rb",
    "test/cli/cli_basic_test.rb",
    "test/misc/binary_search_test.rb",
    "test/misc/misc_pascal_test.rb",
    "test/test_helper.rb",
    "test/test_lilutils.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
  end
end

